version: "3.9"

services:
  rootcomponent:
    image: rootcomponent:0.1
    ports:
      - "8090:8090"
    tty: true
    container_name: rootcomponent
    working_dir: /rootcomponent
    network_mode: "host"
    depends_on:
      - boardcomponent
    stdin_open: true

  boardcomponent:
    image: boardcomponent:0.1
    ports:
      - "8081:8081"
    tty: true
    container_name: boardcomponent
    working_dir: /boardcomponent
    network_mode: "host"
    depends_on:
      - db

  # fileiocomponent:
  #   image: fileiocomponent:0.1
  #   ports:
  #     - "8082:8082"
  #   tty: true
  #   container_name: boardcomponent
  #   working_dir: /boardcomponent
  #   network_mode: "host"

  db:
    image: postgres:latest
    restart: always
    # container_name: database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: mydb
      # POSTGRES_HOST: database
      # POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

    # depends_on:
    #   - pgadmin

  # pgadmin:
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"

volumes:
  postgres_data:
  mongo-data:
  # pgdata:
