version: "3.9"

services:
  rootcomponent:
    image: rootcomponent:0.1
    ports:
      - "8090:8090"
    tty: true
    container_name: rootcomponent
    working_dir: /rootcomponent
    network_mode: "host"
    depends_on:
      - boardcomponent
    stdin_open: true

  boardcomponent:
    image: boardcomponent:0.1
    ports:
      - "8081:8081"
    tty: true
    container_name: boardcomponent
    working_dir: /boardcomponent
    network_mode: "host"

  fileiocomponent:
    image: fileiocomponent:0.1
    ports:
      - "8082:8082"
    tty: true
    container_name: boardcomponent
    working_dir: /boardcomponent
    network_mode: "host"
