version: "3.9"

services:
  rootcomponent:
    image: rootcomponent:0.1
    ports:
      - "8090:8090"
    tty: true
    container_name: rootcomponent
    working_dir: /rootcomponent
    network_mode: "host"
    depends_on:
      - boardcomponent
      - db
    stdin_open: true

  boardcomponent:
    image: boardcomponent:0.1
    ports:
      - "8081:8081"
    tty: true
    container_name: boardcomponent
    working_dir: /boardcomponent
    network_mode: "host"

  # fileiocomponent:
  #   image: fileiocomponent:0.1
  #   ports:
  #     - "8082:8082"
  #   tty: true
  #   container_name: boardcomponent
  #   working_dir: /boardcomponent
  #   network_mode: "host"

  db:
    image: postgres:13
    restart: always
    container_name: database
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: tbl
      POSTGRES_HOST: database
      POSTGRES_PORT: 5432
    ports:
      - "5432:5432"
    depends_on:
      - pgadmin

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"

volumes:
  pgdata:
